services:
  backend:
    container_name: backend
    ports:
      - "8080:8080"
    build:
      context: .
    depends_on:
      - redis
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  redis_data: